version: '3.8'

services:
  # Backend API
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - ./deployments:/var/www
    networks:
      - madahost-local

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - madahost-local

  # Nginx pour simulation sous-domaines
  nginx:
    image: nginx:alpine
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
      - ./deployments:/var/www
    depends_on:
      - api
    networks:
      - madahost-local

networks:
  madahost-local:
    driver: bridge

volumes:
  deployments: