version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    container_name: madahost_api
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env.production
    volumes:
      - /var/www/deployments:/var/www/deployments
      - ./backend/logs:/app/logs
      - build_cache:/app/build_cache
    networks:
      - madahost_network

  nginx:
    image: nginx:alpine
    restart: always
    container_name: madahost_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/madahost.conf:/etc/nginx/conf.d/madahost.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
      - /var/www/deployments:/var/www/deployments:ro  # ✅ Changé vers deployments
      - nginx_cache:/var/cache/nginx
    networks:
      - madahost_network
    depends_on:
      - api
      - frontend

volumes:
  build_cache:
    driver: local
  nginx_cache:
    driver: local

networks:
  madahost_network:
    driver: bridge